// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress   string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AddNodeRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type AddNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MigratedFileCount int32                  `protobuf:"varint,1,opt,name=migrated_file_count,json=migratedFileCount,proto3" json:"migrated_file_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AddNodeResponse) GetMigratedFileCount() int32 {
	if x != nil {
		return x.MigratedFileCount
	}
	return 0
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress   string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNodeRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type RemoveNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MigratedFileCount int32                  `protobuf:"varint,1,opt,name=migrated_file_count,json=migratedFileCount,proto3" json:"migrated_file_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveNodeResponse) GetMigratedFileCount() int32 {
	if x != nil {
		return x.MigratedFileCount
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\n" +
	"tritontube\"3\n" +
	"\x0eAddNodeRequest\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\"A\n" +
	"\x0fAddNodeResponse\x12.\n" +
	"\x13migrated_file_count\x18\x01 \x01(\x05R\x11migratedFileCount\"6\n" +
	"\x11RemoveNodeRequest\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\"D\n" +
	"\x12RemoveNodeResponse\x12.\n" +
	"\x13migrated_file_count\x18\x01 \x01(\x05R\x11migratedFileCount\"\x12\n" +
	"\x10ListNodesRequest\")\n" +
	"\x11ListNodesResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes2\xf5\x01\n" +
	"\x18VideoContentAdminService\x12B\n" +
	"\aAddNode\x12\x1a.tritontube.AddNodeRequest\x1a\x1b.tritontube.AddNodeResponse\x12K\n" +
	"\n" +
	"RemoveNode\x12\x1d.tritontube.RemoveNodeRequest\x1a\x1e.tritontube.RemoveNodeResponse\x12H\n" +
	"\tListNodes\x12\x1c.tritontube.ListNodesRequest\x1a\x1d.tritontube.ListNodesResponseB\x16Z\x14internal/proto;protob\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_admin_proto_goTypes = []any{
	(*AddNodeRequest)(nil),     // 0: tritontube.AddNodeRequest
	(*AddNodeResponse)(nil),    // 1: tritontube.AddNodeResponse
	(*RemoveNodeRequest)(nil),  // 2: tritontube.RemoveNodeRequest
	(*RemoveNodeResponse)(nil), // 3: tritontube.RemoveNodeResponse
	(*ListNodesRequest)(nil),   // 4: tritontube.ListNodesRequest
	(*ListNodesResponse)(nil),  // 5: tritontube.ListNodesResponse
}
var file_proto_admin_proto_depIdxs = []int32{
	0, // 0: tritontube.VideoContentAdminService.AddNode:input_type -> tritontube.AddNodeRequest
	2, // 1: tritontube.VideoContentAdminService.RemoveNode:input_type -> tritontube.RemoveNodeRequest
	4, // 2: tritontube.VideoContentAdminService.ListNodes:input_type -> tritontube.ListNodesRequest
	1, // 3: tritontube.VideoContentAdminService.AddNode:output_type -> tritontube.AddNodeResponse
	3, // 4: tritontube.VideoContentAdminService.RemoveNode:output_type -> tritontube.RemoveNodeResponse
	5, // 5: tritontube.VideoContentAdminService.ListNodes:output_type -> tritontube.ListNodesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
